### DISCUSSION TITLE
PoC - Running Swirl in an Azure Container Instance

### DISCUSSION THREAD

**Discussion by erikspears** [swirlai/swirl-search#1008] [Show and tell]
# Prerequisites

1. [Azure command line interface](https://learn.microsoft.com/en-us/cli/azure/) (CLI)
2. [Docker app](https://www.docker.com/products/docker-desktop/) and [Docker Compose](https://docs.docker.com/compose/)
3. Azure Cloud Administrator account privileges

# Instructions

## Azure Setup

> [!NOTE]  
> *In this example, we name the Azure Resource Group `swlat00-rg` ; however, that specific name isn't meaningful to the deployment. You may use another name for your Resource Group.*

* Login to Azure:
  `az login`
  `az account set --subscription  "name or ID of your subscription"`
* Create an Azure Resource Group:
  `az group create --name <resource-group-name>  --location eastus`
* Create an ACR in the Resource Group:
  `az acr create --resource-group <resource-group-name> --name <acr-name> --sku Basic`
* Login to the ACR:
  `az acr login --name <acr-name>`

## Docker Setup

* Pull the necessary Docker images:
  `docker pull swirlai/swirl-search:latest`
  `docker pull redis:latest`
* Tag the pulled Docker images:
  `docker tag swirlai/swirl-search:latest <acr-name>.azurecr.io/swirl:latest`
  `docker tag redis:latest <acr-name>.azurecr.io/redis:latest`
* Push the Docker images:
  `docker push <acr-name>.azurecr.io/swirl:latest`
  `docker push <acr-name>.azurecr.io/redis:latest`
* Create an Azure Container Instance (ACI) context in Docker and use it by default:

  `docker context create aci swlat00-aci-ctx`
  `docker context use swlat00-aci-ctx`

### Microsoft 365

* If you intend to search Microsoft sources with Swirl:
  * Follow the steps in the [Swirl M365 Guide](https://docs.swirl.today/M365-Guide.html) to add a new App Registration in your Azure Portal
  * Export the environment variables as below with information from that process:

    ```
    export MSAL_APP_ID=<app-id-of-registered-app>
    export MSAL_CB_PORT=8000
    export MSAL_HOST=localhost
    export MSAL_TENANT_ID=<tenant-id-of-your-tenant>
    ```

### ChatGPT

* If you intent to use Swirl's ChatGPT integrations, including Retrieval Augmented Generation (RAG), export your OpenAI API key:

  ```
  export OPENAI_API_KEY=<your-openai-api-key>
  ```
* Check out [OpenAI's YouTube video](https://youtu.be/nafDyRsVnXU?si=YpvyaRvhX65vtBrb) if you don't have an OpenAI API Key and want to obtain one.

## Docker Container Setup

* Create the following Docker Compose file locally and name it: `docker-compose.yaml`

  ```
  version: '3'
   
  services:
    redis:
      image: redis
    swirl:
      image: swirlai/swirl-search:latest
      ports:
        - "8000:8000"
      command: >
        sh -c 'rm -fr ./.swirl && python swirl.py setup &&
               /usr/bin/jq ".default" ./config-swirl-demo.db.json | sed -e "s/<msal-app-id>/$MSAL_APP_ID/" \
                   -e "s/<msal-tenant-id>/$MSAL_TENANT_ID/" \
                   -e "s/<msal-port>/$MSAL_CB_PORT/" \
                   -e "s/<msal-host>/$MSAL_HOST/" > static/api/config/default &&
               python swirl.py start celery-worker celery-beats &&
               daphne -b 0.0.0.0 -p 8000 swirl_server.asgi:application'
      deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 4G
      environment: # Environment variables section
        - OPENAI_API_KEY=${OPENAI_API_KEY} 
        - ALLOWED_HOSTS="*"
        - PROTOCOL=http
        - SWIRL_EXPLAIN=True
        - SQL_ENGINE=django.db.backends.sqlite3
        - SQL_DATABASE=db.sqlite3
        - SQL_USER=user
        - SQL_PASSWORD=password
        - SQL_HOST=localhost
        - SQL_PORT=5432
  ```
* Bring the containers up in Azure (*Note: this will take some time!*):
  `docker compose up`
* Get the Container group name:
  `az container list --resource-group <resource-group-name> --query "[].name" --output tsv`
* Get the IP address of the Container instance:
  az container show --resource-group `<resource-group-name>` --name `<output-from-previous-step>` --query ipAddress.ip --output tsv
* Update the deployment with the instance IP address:
  * Edit the `ALLOWED_HOST` in the Docker Compose to have be the IP address from the previous step:
    `ALLOWED_HOSTS=<ip-address-from-previous-step>`
  * Set the `MSAL_HOST` value to the IP address from the previous step:
    `export MSAL_HOST=<ip-address-from-previous-step> `
* Redeploy the applications:
  `docker compose up`

## Open the Swirl URLs

* You should now be able to go to the following URLs to use the installed Swirl application:
  `http://<ip-address>:8000/swirl`

  `http://<ip-address>:8000/galaxy`

## Open the Containers in Azure

* Optionally, use the Azure Portal to view the Containers (this example Container is called `swirl-search-org-dev-2` below):
<img width="740" alt="aci-1" src="https://github.com/swirlai/swirl-search/assets/98238295/7f17b14d-7ef2-4efb-bca9-99c639dd39fb">
<img width="1078" alt="aci-2" src="https://github.com/swirlai/swirl-search/assets/98238295/3e7aa82f-36e3-43f6-8188-258bbf192303">
<img width="1523" alt="aci-3" src="https://github.com/swirlai/swirl-search/assets/98238295/eb1dbada-d36a-4d44-878e-866a1d3e5396">

<br /><br />

> [!WARNING]  
> **Once the above steps are completed, your deployment is open to the public internet with no SSL and Swirl's default admin user credentials in place!  Please change the Swirl `admin` account password immediately:**  <https://docs.swirl.today/Admin-Guide.html#changing-a-super-user-password>
