### ISSUE TITLE
Where do I correctly define the redis url?

### ISSUE THREAD

**Issue by ovizii** [swirlai/swirl-search#648]
my .env file:
```
CELERY_BROKER_URL='redis://swirl-redis:6379/0'
CELERY_RESULT_BACKEND='redis://swirl-redis:6379/0'
```

my partial docker-compose.yml:

```
services:

  swirl-redis:
    image: redis:7-alpine
    container_name: swirl-redis
    hostname: swirl-redis

```

logs:
```
swirl_1      | Warning: logs directory does not exist, creating it
swirl_1      | Redis is not running or cannot connect!
swirl_1      | Error: Celery requires redis, settings.CELERY_BROKER_URL:redis://redis:6379/0
swirl_1      | settings.CELERY_RESULT_BACKEND:redis://redis:6379/0 but it does not appear to be running,
swirl_1      | please consult the admin guide at https://github.com/swirlai/swirl-search/wiki/3.-Admin-Guide#installation.
swirl_1      | Command start reported an error
```

**Comment by erikspears** [comment]
Hi @ovizii ,

Thanks for reaching out!  That error typically means that redis was not up and running before you started Swirl.  As of Release 2.6, which just came out, Swirl's startup process was changed.  Redis must now be running locally on your systems _before_ you start Swirl.  Please give that a try and let us know?

Thanks,
--Erik

**Comment by erikspears** [comment]
Also, you might find this section of our Quick Start guide helpful for getting up and running locally:
https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#local-installation

**Comment by ovizii** [comment]
oh, and I apologize, I jsut noticed you have enabled discussions for this project. Feel free to move this as its not really an issue. I will post in discussions next time.

**Comment by ovizii** [comment]
In case it helps, here's my docker-compose.yml

```
version: '3.9'
 
services:

  swirl-redis:
    image: redis:7-alpine
    container_name: swirl-redis
    hostname: swirl-redis
    restart: "no"
    volumes:
      - ./data/redis:/data
    networks:
      - swirl
    cpus: 1
    mem_limit: 512M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

# https://github.com/swirlai/swirl-search
  swirl:
    image: swirlai/swirl-search:latest
    ports:
      - "8100:8000"
    networks:
      - swirl
    cpus: 2
    mem_limit: 2G
    command: >
      sh -c 'rm -fr ./.swirl && python swirl.py setup &&
             /usr/bin/jq ".default" ./config-swirl-demo.db.json | sed -e "s/<msal-app-id>/$MSAL_APP_ID/" \
                 -e "s/<msal-tenant-id>/$MSAL_TENANT_ID/" \
                 -e "s/<msal-port>/$MSAL_CB_PORT/" \
                 -e "s/<msal-host>/$MSAL_HOST/" > static/api/config/default &&
             python swirl.py start celery-worker celery-beats &&
             daphne -b 0.0.0.0 -p 8000 swirl_server.asgi:application'
             

networks:
  swirl:
    external: true
    name: swirl
```

and the .env file

```
SECRET_KEY=redacted
ALLOWED_HOSTS='10.10.10.10'
PROTOCOL=http
SWIRL_EXPLAIN=True
SQL_ENGINE=django.db.backends.sqlite3
SQL_DATABASE=db.sqlite3
SQL_USER=user
SQL_PASSWORD=password
SQL_HOST=localhost
SQL_PORT=5432
MICROSOFT_CLIENT_ID=''
MICROSOFT_CLIENT_SECRET=''
MICROSOFT_REDIRECT_URI='http://localhost:8000/swirl/microsoft-callback'
CELERY_BROKER_URL='redis://swirl-redis:6379/0'
CELERY_RESULT_BACKEND='redis://swirl-redis:6379/0'
```
